atomisp2: css2401a0_v21: compile fixes due to overly large stack
BZ: 146545

Fix compilation errors like
css2401a0_v21_build/css/runtime/debug/src/ia_css_debug.c:1942:1:
error: the frame size of 3504 bytes is larger than 2048 bytes
by allocating big structures dynamically.

Change-Id: I83614c62c918e09309422407b370fcf31c58a05a
Signed-off-by: Tuukka Toivonen <tuukka.toivonen@intel.com>
Signed-off-by: Antti Laakso <antti.laakso@intel.com>