atomisp2: css2400b0_v21: fix compilation error
BZ: 146545

ia_css_debug.h uses prototype for sh_css_vprint() from
sh_css_internal.h and includes it. Therefore sh_css_internal.h
must not include ia_css_debug.h even indirectly or we get an
circular dependency. However, the following was happening:

In file included from hive_isp_css_include/assert_support.h:65:0,
                 from hive_isp_css_2400_system/host/hmem_private.h:28,
                 from hive_isp_css_include/hmem.h:52,
                 from isp/kernels/bh/bh_2/ia_css_bh_param.h:34,
                 from hive_isp_css_kernel/pipeline/pipeline_global.h:64,
                 from hive_isp_css_kernel/pipeline/host/pipeline_local.h:26,
                 from hive_isp_css_include/pipeline.h:50,
                 from sh_css_internal.h:58,
runtime/debug/interface/ia_css_debug.h:2:2: includes again sh_css_internal.h
-> circular dependency

Original patch name "Changes for patch 4055" with
Orig-Change-Id: I486755dc16f4d00a38270062a61b64c5c861bc91

Change-Id: I5b93610f80409fa2a1e96f6d0fdef52e4260b088
Orig-Change-Id: I0d977dda9b4882039dc553d38e776e643d83d42d
Signed-off-by: Tuukka Toivonen <tuukka.toivonen@intel.com>
Signed-off-by: Antti Laakso <antti.laakso@intel.com>