atomisp2: css2401a0_v21: compile fixes due to overly large stack
BZ: 149516

Fix compilation errors like
css2401a0_v21_build/css/runtime/debug/src/ia_css_debug.c:1942:1:
error: the frame size of 3504 bytes is larger than 2048 bytes
by allocating big structures dynamically.

Change-Id: I21f49037fa6fe391ba75f199ae7eb5f2ae820cf2
Signed-off-by: Tuukka Toivonen <tuukka.toivonen@intel.com>
Acked-by: Sakari Ailus <sakari.ailus@linux.intel.com>
Signed-off-by: Antti Laakso <antti.laakso@intel.com>